# Generated by Django 5.2.17 on 2026-09-25 07:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Katalog guruhi',
                'verbose_name_plural': 'Katalog guruhlari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_]+$', 'Faqat kichik lotin harflari, raqam va _')], verbose_name='Kalit (id)')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('unit', models.CharField(choices=[('dona', 'dona'), ('m', 'm'), ('m²', 'm²'), ('m³', 'm³'), ('kg', 'kg'), ('seksiya', 'seksiya'), ('komplekt', 'komplekt')], max_length=20, verbose_name='Birlik')),
                ('group', models.CharField(choices=[('Beton', 'Beton'), ('Pol', 'Pol'), ('Devor', 'Devor'), ('Shift', 'Shift')], max_length=20, verbose_name='Guruh')),
                ('src1', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='1-manba')),
                ('src2', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='2-manba')),
                ('src3', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='3-manba')),
                ('sources', models.CharField(blank=True, max_length=200, verbose_name='Manbalar nomi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Material narxi',
                'verbose_name_plural': 'Material narxlari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_]+$', 'Faqat kichik lotin harflari, raqam va _')], verbose_name='Kalit (id)')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('unit', models.CharField(choices=[('dona', 'dona'), ('m', 'm'), ('m²', 'm²'), ('m³', 'm³'), ('kg', 'kg'), ('seksiya', 'seksiya'), ('komplekt', 'komplekt')], default='dona', max_length=20, verbose_name='Birlik')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name="Narx, so'm")),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name="O'rnatish, soat/birlik")),
                ('ask_dims', models.BooleanField(default=False, verbose_name="O'lcham so'ralsin")),
                ('ask_watt', models.BooleanField(default=False, verbose_name="Quvvat so'ralsin")),
                ('active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='smeta.cataloggroup', verbose_name='Guruh')),
            ],
            options={
                'verbose_name': 'Katalog elementi',
                'verbose_name_plural': 'Katalog elementlari',
                'ordering': ['group__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CatalogVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150, verbose_name='Turi')),
                ('price', models.DecimalField(decimal_places=0, max_digits=14, verbose_name="Narx, so'm")),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name="Soat (bo'sh — elementniki)")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='smeta.catalogitem')),
            ],
            options={
                'verbose_name': 'Turi',
                'verbose_name_plural': 'Turlari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('floor', models.CharField(choices=[('laminat', 'Laminat'), ('kafel', 'Kafel'), ('linoleum', 'Linoleum'), ('parket', 'Parket'), ('yoq', "O'zgarmaydi")], default='laminat', max_length=20, verbose_name='Pol')),
                ('wall', models.CharField(choices=[('boyoq', "Bo'yoq (shpaklyovka bilan)"), ('oboy', 'Oboy'), ('kafel', "Kafel (to'liq balandlik)"), ('gipsokarton', 'Gipsokarton'), ('yoq', "O'zgarmaydi")], default='boyoq', max_length=20, verbose_name='Devor')),
                ('ceil', models.CharField(choices=[('shift_boyoq', "Bo'yoq"), ('natyajnoy', 'Natyajnoy shift'), ('gipsokarton', 'Gipsokarton'), ('armstrong', 'Armstrong'), ('yoq', "O'zgarmaydi")], default='shift_boyoq', max_length=20, verbose_name='Shift')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('suggestions', models.ManyToManyField(blank=True, to='smeta.catalogitem', verbose_name='Tavsiya elementlar')),
            ],
            options={
                'verbose_name': 'Xona turi',
                'verbose_name_plural': 'Xona turlari',
                'ordering': ['order', 'id'],
            },
        ),
    ]
