# Generated by Django 5.2.17 on 2026-09-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0003_malumotnoma_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cataloggroup',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nomi (ruscha)'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='name_ru',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nomi (ruscha)'),
        ),
        migrations.AddField(
            model_name='catalogvariant',
            name='label_ru',
            field=models.CharField(blank=True, max_length=150, verbose_name='Turi (ruscha)'),
        ),
        migrations.AddField(
            model_name='material',
            name='name_ru',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nomi (ruscha)'),
        ),
        migrations.AddField(
            model_name='material',
            name='sources_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Manbalar nomi (ruscha)'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nomi (ruscha)'),
        ),
    ]
