# Generated by Django 5.2.17 on 2026-09-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0005_ruscha_nomlar_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='ceil',
            field=models.CharField(choices=[('shift_boyoq', "Suv emulsiyali bo'yoq"), ('shift_moyli', "Moyli bo'yoq"), ('shift_akril', "Akril bo'yoq"), ('natyajnoy', 'Natyajnoy shift'), ('gipsokarton', 'Gipsokarton'), ('armstrong', 'Armstrong'), ('plastik', 'Plastik shift'), ('yoq', "O'zgarmaydi")], default='shift_boyoq', max_length=20, verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='floor',
            field=models.CharField(choices=[('laminat', 'Laminat'), ('kafel', 'Kafel'), ('linoleum', 'Linoleum'), ('relin', 'Relin'), ('parket', 'Parket'), ('yoq', "O'zgarmaydi")], default='laminat', max_length=20, verbose_name='Pol'),
        ),
    ]
