# Generated by Django 5.2.17 on 2026-09-29 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0007_yangi_materiallar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='Telegram username')),
                ('first_name', models.CharField(blank=True, max_length=128, verbose_name='Ismi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Ulangan')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Oxirgi kirish')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Telegram hisobi',
                'verbose_name_plural': 'Telegram hisoblari',
            },
        ),
    ]
