# Generated by Django 5.2.17 on 2026-10-06 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smeta', '0008_telegram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Telefon raqami')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profillar',
            },
        ),
        migrations.CreateModel(
            name='ResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('phone', 'Telefon raqami'), ('login', 'Login')], max_length=10, verbose_name='Usul')),
                ('identifier', models.CharField(max_length=64, verbose_name='Kiritilgan qiymat')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan')),
                ('handled', models.BooleanField(default=False, verbose_name='Hal qilindi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reset_requests', to=settings.AUTH_USER_MODEL, verbose_name="Foydalanuvchi (topilgan bo'lsa)")),
            ],
            options={
                'verbose_name': "Parolni tiklash so'rovi",
                'verbose_name_plural': "Parolni tiklash so'rovlari",
                'ordering': ['handled', '-created'],
            },
        ),
    ]
